sdk/__tests__/jest-setup-file.ts
sdk/__tests__/port/in/Security.test.ts
sdk/src/app/usecase/command/security/operations/executeHoldByPartition/ExecuteHoldByPartitionCommand.ts
sdk/src/app/usecase/command/security/operations/executeHoldByPartition/ExecuteHoldByPartitionCommandHandler.ts
sdk/src/app/usecase/command/security/operations/hold/createHoldFromByPartition/CreateHoldFromByPartitionCommandHandler.ts
sdk/src/port/in/Security.ts
sdk/src/port/in/request/ExecuteHoldByPartitionRequest.ts
sdk/src/port/out/TransactionAdapter.ts
sdk/src/port/out/hs/HederaTransactionAdapter.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts

feat: fixes and hold sdk test

---

sdk/README.md

docs: add hold operations details to sdk/README.md

---

contracts/scripts/businessLogicResolver.ts
contracts/scripts/commands/CreateConfigurationsForDeployedContractsCommand.ts

fix: remove unused facets from bond facet list

---

contracts/contracts/layer_0/clearing/ClearingStorageWrapper1.sol
contracts/contracts/layer_1/interfaces/clearing/IClearing.sol

feat: clearing storage interface

---

contracts/contracts/layer_0/clearing/ClearingStorageWrapper1.sol
contracts/contracts/layer_1/clearing/Clearing.sol
contracts/contracts/layer_1/interfaces/clearing/IClearing.sol

feat:  implementation of getClearingCountForByPartition, getClearingsIdForByPartition and getClearingForByPartition

---

contracts/contracts/layer_0/adjustBalances/AdjustBalancesStorageWrapper1.sol
contracts/contracts/layer_0/adjustBalances/AdjustBalancesStorageWrapper2.sol
contracts/contracts/layer_0/clearing/ClearingStorageWrapper1.sol
contracts/contracts/layer_0/clearing/ClearingStorageWrapper2.sol
contracts/contracts/layer_0/context/LocalContext.sol
contracts/contracts/layer_1/clearing/Clearing.sol
contracts/contracts/layer_1/clearing/ClearingFacet.sol
contracts/contracts/layer_1/clearing/ClearingOperationFacet.sol
contracts/contracts/layer_1/constants/resolverKeys.sol
contracts/contracts/layer_1/interfaces/clearing/IClearing.sol
contracts/contracts/layer_1/interfaces/clearing/IClearingOperation.sol

feat: approve, cancel and reclaim operations

---

contracts/contracts/layer_0/clearing/ClearingStorageWrapper1.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Basic.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Operator.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410ProtectedPartitions.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Standard.sol
contracts/contracts/layer_1/ERC1400/ERC1594/ERC1594.sol
contracts/contracts/layer_1/ERC1400/ERC20/ERC20.sol
contracts/contracts/layer_1/clearing/ClearingFacet.sol
contracts/contracts/layer_1/clearing/ClearingOperationFacet.sol
contracts/contracts/layer_1/common/Common.sol
contracts/contracts/layer_1/hold/Hold.sol
contracts/contracts/layer_1/interfaces/clearing/IClearing.sol

feat: impacted methods

---

sdk/__tests__/port/in/Kyc.test.ts
sdk/src/app/usecase/command/security/operations/clearing/activateClearing/ActivateClearingCommand.ts
sdk/src/app/usecase/command/security/operations/clearing/activateClearing/ActivateClearingCommandHandler.ts
sdk/src/app/usecase/command/security/operations/clearing/deactivateClearing/DeactivateClearingCommand.ts
sdk/src/app/usecase/command/security/operations/clearing/deactivateClearing/DeactivateClearingCommandHandler.ts
sdk/src/core/Injectable.ts
sdk/src/domain/context/security/SecurityRole.ts
sdk/src/port/in/Security.ts
sdk/src/port/in/request/ActivateClearingRequest.ts
sdk/src/port/in/request/DeactivateClearingRequest.ts
sdk/src/port/in/request/index.ts
sdk/src/port/out/TransactionAdapter.ts
sdk/src/port/out/hs/HederaTransactionAdapter.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts

feat: activate and deactivate functions to sdk

---

sdk/src/app/usecase/command/bond/create/CreateBondCommandHandler.ts
sdk/src/app/usecase/command/equity/create/CreateEquityCommandHandler.ts
sdk/src/port/out/TransactionAdapter.ts
sdk/src/port/out/hs/HederaTransactionAdapter.ts

fix: creation of securities with HWC

---

sdk/README.md

feat: clearing documentation

---

contracts/.solhint.json

`style: enforce ordering rule in Solhint configuration`

---

contracts/contracts/factory/Factory.sol
contracts/contracts/layer_0/adjustBalances/AdjustBalancesStorageWrapper1.sol
contracts/contracts/layer_0/adjustBalances/AdjustBalancesStorageWrapper2.sol
contracts/contracts/layer_0/clearing/ClearingStorageWrapper1.sol
contracts/contracts/layer_0/clearing/ClearingStorageWrapper2.sol
contracts/contracts/layer_0/context/LocalContext.sol
contracts/contracts/layer_1/clearing/ClearingActionsFacet.sol
contracts/contracts/layer_1/clearing/ClearingHoldCreationFacet.sol
contracts/contracts/layer_1/clearing/ClearingReadFacet.sol
contracts/contracts/layer_1/clearing/ClearingRedeemFacet.sol
contracts/contracts/layer_1/clearing/ClearingTransferFacet.sol
contracts/contracts/layer_1/interfaces/clearing/IClearing.sol
contracts/contracts/layer_1/interfaces/clearing/IClearingActions.sol
contracts/contracts/layer_1/interfaces/clearing/IClearingHoldCreation.sol
contracts/contracts/layer_1/interfaces/clearing/IClearingRead.sol
contracts/contracts/layer_1/interfaces/clearing/IClearingRedeem.sol
contracts/contracts/layer_1/interfaces/clearing/IClearingTransfer.sol
contracts/contracts/layer_2/adjustBalances/AdjustBalances.sol
contracts/contracts/layer_2/interfaces/adjustBalances/IAdjustBalances.sol
contracts/contracts/test/testTimeTravel/facetsTimeTravel/ClearingHoldCreationFacetTimeTravel.sol
contracts/contracts/test/testTimeTravel/facetsTimeTravel/ClearingReadFacetTimeTravel.sol
contracts/contracts/test/testTimeTravel/facetsTimeTravel/ClearingRedeemFacetTimeTravel.sol
contracts/contracts/test/testTimeTravel/facetsTimeTravel/ClearingTransferFacetTimeTravel.sol

clearing facets split

---

contracts/contracts/layer_1/ERC1400/ERC20/ERC20.sol
contracts/contracts/layer_1/interfaces/ERC1400/IERC20.sol
contracts/test/demo/Demo.test.Hedera.ts
contracts/test/unitTests/layer_1/ERC1400/ERC20/erc20.test.ts
contracts/test/unitTests/layer_2/ERC1400/erc1400.test.ts

feat: remove external methods non-adjusted decimals

---

contracts/contracts/layer_1/interfaces/snapshots/ISnapshots.sol
contracts/contracts/layer_1/snapshots/Snapshots.sol
contracts/contracts/layer_2/adjustBalances/AdjustBalances.sol
contracts/contracts/layer_2/interfaces/adjustBalances/IAdjustBalances.sol
contracts/test/unitTests/layer_2/snapshots/snapshots.test.ts

feat: remove externals methods that return abafs

---

web/src/i18n/en/security/details.ts
web/src/theme/components/Forms/Toggle.ts
web/src/theme/components/Tabs.ts
web/src/utils/helpers.ts
web/src/views/Dashboard/Dashboard.tsx
web/src/views/DigitalSecuritiesList/DigitalSecuritiesList.tsx
web/src/views/DigitalSecurityDetails/Components/AdminActionsButtons.tsx
web/src/views/DigitalSecurityDetails/Components/Coupons/__tests__/__snapshots__/Coupons.test.tsx.snap
web/src/views/DigitalSecurityDetails/Components/DangerZone.tsx
web/src/views/DigitalSecurityDetails/Components/Details.tsx
web/src/views/DigitalSecurityDetails/Components/Dividends/__tests__/__snapshots__/Dividends.test.tsx.snap
web/src/views/DigitalSecurityDetails/Components/KYC/KYC.tsx
web/src/views/DigitalSecurityDetails/Components/RoleManagement/RoleManagement.tsx
web/src/views/DigitalSecurityDetails/Components/RoleManagement/__tests__/__snapshots__/RoleManagement.test.tsx.snap
web/src/views/DigitalSecurityDetails/Components/Tabs/Control.tsx
web/src/views/DigitalSecurityDetails/Components/Tabs/CorporateActions.tsx
web/src/views/DigitalSecurityDetails/Components/Tabs/Management.tsx
web/src/views/DigitalSecurityDetails/Components/Tabs/Operations.tsx
web/src/views/DigitalSecurityDetails/Components/VotingRights/__tests__/__snapshots__/VotingRights.test.tsx.snap
web/src/views/DigitalSecurityDetails/Components/__tests__/AdminActionsButtons.test.tsx
web/src/views/DigitalSecurityDetails/Components/__tests__/DangerZone.test.tsx
web/src/views/DigitalSecurityDetails/Components/__tests__/__snapshots__/ActionsButtons.test.tsx.snap
web/src/views/DigitalSecurityDetails/Components/__tests__/__snapshots__/AdminActionsButtons.test.tsx.snap
web/src/views/DigitalSecurityDetails/Components/__tests__/__snapshots__/DangerZone.test.tsx.snap
web/src/views/DigitalSecurityDetails/Components/__tests__/__snapshots__/Details.test.tsx.snap
web/src/views/DigitalSecurityDetails/DigitalSecurityDetails.tsx
web/src/views/DigitalSecurityDetails/__tests__/__snapshots__/DigitalSecurityDetails.test.tsx.snap

feat: [BBND-696] revamping ui

---

web/src/hooks/queries/useClearingOperations.ts
web/src/services/SDKService.ts
web/src/views/DigitalSecurityDetails/Components/ClearingOperations/ClearingOperationList.tsx

feat: update clearing operations functions

---

web/src/hooks/queries/useClearingOperations.ts
web/src/i18n/en/security/details.ts
web/src/services/SDKService.ts
web/src/views/DigitalSecurityDetails/Components/Balance.tsx
web/src/views/DigitalSecurityDetails/Components/__tests__/__snapshots__/Balance.test.tsx.snap
web/src/views/DigitalSecurityDetails/__tests__/__snapshots__/DigitalSecurityDetails.test.tsx.snap

feat: add cleared balance

---

web/src/views/DigitalSecurityDetails/Components/KYC/KYC.tsx

fix: adjust KYC dates

---

web/src/i18n/en/security/clearingOperations.ts
web/src/theme/components/Tabs.ts
web/src/views/DigitalSecurityDetails/Components/ClearingOperations/ClearingOperationList.tsx

fix: change to table in clearing operations list

---

contracts/contracts/layer_0/common/ArrayLib.sol
contracts/contracts/layer_0/context/LocalContext.sol
contracts/contracts/layer_0/core/accessControl/AccessControlStorageWrapper.sol
contracts/contracts/layer_0/core/externalControlLists/ExternalControlListManagementStorageWrapper.sol
contracts/contracts/layer_1/accessControl/AccessControl.sol
contracts/contracts/layer_1/externalControlLists/ExternalControlListManagement.sol
contracts/contracts/layer_1/interfaces/accessControl/IAccessControlStorageWrapper.sol
contracts/test/unitTests/layer_1/accessControl/accessControl.test.ts

Improve gas consumption in roles assignation and external control list.

---

sdk/__tests__/jest-setup-file.ts
sdk/__tests__/port/in/ExternalPauses.test.ts
sdk/src/app/usecase/command/security/externalPauses/addExternalPause/AddExternalPauseCommand.ts
sdk/src/app/usecase/command/security/externalPauses/addExternalPause/AddExternalPauseCommandHandler.ts
sdk/src/app/usecase/command/security/externalPauses/removeExternalPause/RemoveExternalPauseCommand.ts
sdk/src/app/usecase/command/security/externalPauses/removeExternalPause/RemoveExternalPauseCommandHandler.ts
sdk/src/core/Injectable.ts
sdk/src/port/in/ExternalPausesManagement.ts
sdk/src/port/in/request/AddExternalPauseRequest.ts
sdk/src/port/in/request/RemoveExternalPauseRequest.ts
sdk/src/port/in/request/index.ts
sdk/src/port/out/TransactionAdapter.ts
sdk/src/port/out/hs/HederaTransactionAdapter.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts

[BBND-792|BBND-793] Feat: added removeExternalPause and addExternalPause

---

sdk/src/app/usecase/command/security/externalPauses/mock/setPaused/SetPausedMockCommand.ts
sdk/src/app/usecase/command/security/externalPauses/mock/setPaused/SetPausedMockCommandHandler.ts
sdk/src/app/usecase/query/security/externalPauses/mock/isPaused/IsPausedMockQuery.ts
sdk/src/app/usecase/query/security/externalPauses/mock/isPaused/IsPausedMockQueryHandler.ts
sdk/src/core/Injectable.ts
sdk/src/port/in/ExternalPausesManagement.ts
sdk/src/port/in/request/IsPausedMockRequest.ts
sdk/src/port/in/request/SetPausedMockRequest.ts
sdk/src/port/in/request/index.ts
sdk/src/port/out/TransactionAdapter.ts
sdk/src/port/out/rpc/RPCQueryAdapter.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts

-   [x] New feature ✨
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

[BBND-800] Feat: Implement external pause mock contract to sdk

---

web/src/i18n/en/externalControlList/index.ts
web/src/layouts/components/Sidebar.tsx
web/src/views/AddExternalControl/AddExternalControl.tsx
web/src/views/CreateExternalControl/CreateExternalControl.tsx
web/src/views/ExternalControlList/Components/Header.tsx

-   [x] Bug fix 🐞
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

fix: improve UI

---

sdk/__tests__/fixtures/externalPauses/ExternalPausesFixture.ts
sdk/src/app/usecase/command/security/externalPauses/addExternalPause/AddExternalPauseCommandHandler.ts
sdk/src/app/usecase/command/security/externalPauses/addExternalPause/AddExternalPauseCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/externalPauses/mock/createExternalPauseMock/CreateExternalPauseMockCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/externalPauses/mock/setPaused/SetPausedMockCommandHandler.ts
sdk/src/app/usecase/command/security/externalPauses/mock/setPaused/SetPausedMockCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/externalPauses/removeExternalPause/RemoveExternalPauseCommandHandler.ts
sdk/src/app/usecase/command/security/externalPauses/removeExternalPause/RemoveExternalPauseCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/externalPauses/updateExternalPauses/UpdateExternalPausesCommandHandler.ts
sdk/src/app/usecase/command/security/externalPauses/updateExternalPauses/UpdateExternalPausesCommandHandler.unit.test.ts
sdk/src/app/usecase/query/security/externalPauses/getExternalPausesCount/GetExternalPausesCountQueryHandler.ts
sdk/src/app/usecase/query/security/externalPauses/getExternalPausesCount/GetExternalPausesCountQueryHandler.unit.test.ts
sdk/src/app/usecase/query/security/externalPauses/getExternalPausesMembers/GetExternalPausesMembersQueryHandler.ts
sdk/src/app/usecase/query/security/externalPauses/getExternalPausesMembers/GetExternalPausesMembersQueryHandler.unit.test.ts
sdk/src/app/usecase/query/security/externalPauses/isExternalPause/IsExternalPauseQueryHandler.ts
sdk/src/app/usecase/query/security/externalPauses/isExternalPause/IsExternalPauseQueryHandler.unit.test.ts
sdk/src/app/usecase/query/security/externalPauses/mock/isPaused/IsPausedMockQueryHandler.ts
sdk/src/app/usecase/query/security/externalPauses/mock/isPaused/IsPausedMockQueryHandler.unit.test.ts
sdk/src/port/in/externalPausesManagement/ExternalPausesManagement.ts
sdk/src/port/in/externalPausesManagement/ExternalPausesManagement.unit.test.ts
sdk/src/port/in/index.ts
sdk/src/port/out/hs/HederaTransactionAdapter.ts

-   [x] Refactor 🔧
-   [ ] 18
-   [x] 20
-   [ ] 22
-   [ ] 23
-   [x] Style Guidelines followed ✅
-   [x] **Linters** - No New Warnings ⚠️
-   [x] Effective Tests Added ✔️
-   [x] Local Tests Pass ✅

[BBND-826|827] Feat: refactored code to use new services and added unit tests

---

sdk/README.md

-   [x] Documentation update 📖
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23
-   [x] Documentation Updated 📚

chore: Add external pauses management documentation

---

sdk/README.md

-   [x] Documentation update 📖
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23
-   [x] Documentation Updated 📚

chore: add external control list management documentation

---

contracts/package-lock.json
contracts/package.json
package-lock.json
package.json
sdk/package-lock.json
sdk/package.json
web/package.json
web/yarn.lock

Update package versions to 1.13.0 across all modules and lock files

chore: update versions to 1.13.0 and lock files

---

README.md

Add custodian integration section to README
-   [X] Documentation update 📖
-   [X] Local Tests (npm run test)
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23
-   [X] Style Guidelines followed ✅
-   [X] Self-Reviewed 👀
-   [X] Documentation Updated 📚
-   [X] **Linters** - No New Warnings ⚠️
-   [X] Effective Tests Added ✔️
-   [X] Local Tests Pass ✅
-   [X] No reduction of **Coverage**

[BBND-853] Add custodian integration section to README

---

sdk/__tests__/fixtures/kyc/KycFixture.ts
sdk/src/app/usecase/command/security/kyc/activateInternalKyc/ActivateInternalKycCommand.ts
sdk/src/app/usecase/command/security/kyc/activateInternalKyc/ActivateInternalKycCommandHandler.ts
sdk/src/app/usecase/command/security/kyc/activateInternalKyc/ActivateInternalKycCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/kyc/deactivateInternalKyc/DeactivateInternalKycCommand.ts
sdk/src/app/usecase/command/security/kyc/deactivateInternalKyc/DeactivateInternalKycCommandHandler.ts
sdk/src/app/usecase/command/security/kyc/deactivateInternalKyc/DeactivateInternalKycCommandHandler.unit.test.ts
sdk/src/app/usecase/query/security/kyc/isInternalKycActivated/IsInternalKycActivatedQuery.ts
sdk/src/app/usecase/query/security/kyc/isInternalKycActivated/IsInternalKycActivatedQueryHandler.ts
sdk/src/app/usecase/query/security/kyc/isInternalKycActivated/IsInternalKycActivatedQueryHandler.unit.test.ts
sdk/src/core/Injectable.ts
sdk/src/port/in/index.ts
sdk/src/port/in/kyc/Kyc.ts
sdk/src/port/in/kyc/Kyc.unit.test.ts
sdk/src/port/in/request/index.ts
sdk/src/port/in/request/security/kyc/ActivateInternalKycRequest.ts
sdk/src/port/in/request/security/kyc/DeactivateInternalKycRequest.ts
sdk/src/port/in/request/security/kyc/IsInternalKycActivatedRequest.ts
sdk/src/port/out/TransactionAdapter.ts
sdk/src/port/out/rpc/RPCQueryAdapter.ts

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

feat: internal kyc methods

---

sdk/README.md

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

chore: update documentation

---

web/src/i18n/en/landing.ts
web/src/i18n/en/security/createBond.ts
web/src/views/CreateBond/__tests__/__snapshots__/CreateBond.test.tsx.snap
web/src/views/Landing/__tests__/__snapshots__/Landing.test.tsx.snap

- Metamask Instructions with wrong links
- Corrected a translation issue in the bond creation process
-   [x] Bug fix 🐞
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

fix: [BBND-931]instructions with wrong links and locale missing

---

contracts/package-lock.json
contracts/package.json
package-lock.json
package.json
sdk/package-lock.json
sdk/package.json
web/package.json

Update modules versions and lock files.
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

chore: update versions and lock files

---

contracts/contracts/layer_0/ERC1400/ERC1410/ERC1410ControllerStorageWrapper.sol
contracts/contracts/layer_0/ERC1400/ERC1410/ERC1410StandardStorageWrapper.sol
contracts/contracts/layer_0/ERC3643/ERC3643StorageWrapper1.sol
contracts/contracts/layer_0/ERC3643/ERC3643StorageWrapper2.sol
contracts/contracts/layer_0/constants/values.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Basic.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Operator.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410ProtectedPartitions.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Standard.sol
contracts/contracts/layer_1/ERC1400/ERC1594/ERC1594.sol
contracts/contracts/layer_1/ERC1400/ERC1594/ERC1594StorageWrapper.sol
contracts/contracts/layer_1/ERC1400/ERC20/ERC20.sol
contracts/contracts/layer_1/ERC3643/ERC3643.sol
contracts/contracts/layer_1/clearing/ClearingHoldCreationFacet.sol
contracts/contracts/layer_1/clearing/ClearingRedeemFacet.sol
contracts/contracts/layer_1/clearing/ClearingTransferFacet.sol
contracts/contracts/layer_1/constants/values.sol
contracts/contracts/layer_1/hold/Hold.sol
contracts/contracts/layer_1/interfaces/ERC3643/IERC3643.sol
contracts/contracts/layer_1/lock/Lock.sol
contracts/scripts/constants.ts
contracts/test/unitTests/layer_1/ERC3643/erc3643.test.ts

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

feat: merge recovery with set address frozen changes

---

contracts/contracts/layer_0/ERC1400/ERC1410/ERC1410ControllerStorageWrapper.sol
contracts/contracts/layer_0/ERC1400/ERC1410/ERC1410StandardStorageWrapper.sol
contracts/contracts/layer_0/ERC3643/ERC3643StorageWrapper1.sol
contracts/contracts/layer_0/ERC3643/ERC3643StorageWrapper2.sol
contracts/contracts/layer_0/constants/values.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Basic.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Controller.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Operator.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410ProtectedPartitions.sol
contracts/contracts/layer_1/ERC1400/ERC1410/ERC1410Standard.sol
contracts/contracts/layer_1/ERC1400/ERC1594/ERC1594.sol
contracts/contracts/layer_1/ERC1400/ERC1594/ERC1594StorageWrapper.sol
contracts/contracts/layer_1/ERC1400/ERC1644/ERC1644.sol
contracts/contracts/layer_1/ERC1400/ERC20/ERC20.sol
contracts/contracts/layer_1/ERC3643/ERC3643.sol
contracts/contracts/layer_1/clearing/ClearingHoldCreationFacet.sol
contracts/contracts/layer_1/clearing/ClearingRedeemFacet.sol
contracts/contracts/layer_1/clearing/ClearingTransferFacet.sol
contracts/contracts/layer_1/constants/values.sol
contracts/contracts/layer_1/hold/Hold.sol
contracts/contracts/layer_1/interfaces/ERC3643/IERC3643.sol
contracts/contracts/layer_1/lock/Lock.sol
contracts/scripts/constants.ts
contracts/test/unitTests/layer_1/ERC1400/ERC1594/erc1594.test.ts
contracts/test/unitTests/layer_1/ERC3643/erc3643.test.ts
sdk/__tests__/fixtures/bond/BondFixture.ts

-   [x] New feature ✨
-   [x] Manual (CLI or web interface)
-   [x] Local GitHub Actions (act pull_request)
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23
-   [x] Style Guidelines followed ✅
-   [x] Self-Reviewed 👀
-   [x] **Linters** - No New Warnings ⚠️
-   [x] Effective Tests Added ✔️
-   [x] Local Tests Pass ✅
-   [x] No reduction of **Coverage**

feat: set address frozen, roles check and recovery

---

sdk/src/app/service/transaction/TransactionService.ts
sdk/src/app/usecase/command/security/externalControlLists/mock/createExternalBlackListMock/CreateExternalBlackListMockCommandHandler.ts
sdk/src/app/usecase/command/security/externalControlLists/mock/createExternalBlackListMock/CreateExternalBlackListMockCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/externalControlLists/mock/createExternalBlackListMock/error/CreateExternalBlackListMockCommandError.ts
sdk/src/app/usecase/command/security/externalControlLists/mock/createExternalWhiteListMock/CreateExternalWhiteListMockCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/externalControlLists/mock/createExternalWhiteListMock/error/CreateExternalWhiteListMockCommandError.ts
sdk/src/app/usecase/command/security/externalPauses/mock/createExternalPauseMock/CreateExternalPauseMockCommandHandler.ts
sdk/src/app/usecase/command/security/externalPauses/mock/createExternalPauseMock/CreateExternalPauseMockCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/externalPauses/mock/createExternalPauseMock/error/CreateExternalPauseMockCommandError.ts

Refactor mock commands to use transaction service and fix bug in contract address retrieval
-   [x] Bug fix 🐞
-   [x] Refactor 🔧
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23
-   [x] Style Guidelines followed ✅
-   [x] Self-Reviewed 👀
-   [x] **Linters** - No New Warnings ⚠️
-   [x] Effective Tests Added ✔️
-   [x] Local Tests Pass ✅
-   [x] No reduction of **Coverage**

feat: mock commands refactor and bug fix

---

sdk/__tests__/fixtures/snapshot/SnapshotFixture.ts
sdk/src/app/usecase/command/security/operations/snapshot/takeSnapshot/TakeSnapshotCommand.ts
sdk/src/app/usecase/command/security/operations/snapshot/takeSnapshot/TakeSnapshotCommandHandler.ts
sdk/src/app/usecase/command/security/operations/snapshot/takeSnapshot/TakeSnapshotCommandHandler.unit.test.ts
sdk/src/app/usecase/command/security/operations/snapshot/takeSnapshot/error/TakeSnapshotCommandError.ts
sdk/src/core/Injectable.ts
sdk/src/port/in/request/index.ts
sdk/src/port/in/request/security/operations/snapshot/TakeSnapshotRequest.ts
sdk/src/port/in/security/Security.ts
sdk/src/port/in/security/Security.unit.test.ts

-   [x] New feature ✨
-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

[BBND-1010] Expose takeSnapshot method to port/in

---

sdk/__tests__/fixtures/network/NetworkFixture.ts
sdk/__tests__/port/in/Bond.test.ts
sdk/__tests__/port/in/Equity.test.ts
sdk/__tests__/port/in/Factory.test.ts
sdk/__tests__/port/in/Kyc.test.ts
sdk/__tests__/port/in/Management.test.ts
sdk/__tests__/port/in/Roles.test.ts
sdk/__tests__/port/in/Security.test.ts
sdk/__tests__/port/in/Ssi.test.ts
sdk/src/app/service/wallet/metamask/MetamaskService.ts
sdk/src/app/service/wallet/metamask/MetamaskService.unit.test.ts
sdk/src/app/usecase/command/bond/create/CreateBondCommandHandler.ts
sdk/src/app/usecase/command/equity/create/CreateEquityCommandHandler.ts
sdk/src/port/in/network/Network.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

refactor: Rpc transaction adpater

---

contracts/package.json
package-lock.json
package.json
sdk/package.json
web/package.json

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

chore: upgrade version to 1.14.3

---

README.md
contracts/README.md
contracts/package.json
contracts/scripts/deploy.ts
contracts/tasks/deploy.ts
package-lock.json
package.json
sdk/package.json
web/.env.sample
web/package.json

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

chore: upgrade to 1.15.1

---

README.md
contracts/README.md

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

chore: improve documentation

---

sdk/src/port/out/hs/HederaTransactionAdapter.ts
sdk/src/port/out/rpc/RPCQueryAdapter.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts

-   [ ] 18
-   [ ] 20
-   [x] 22
-   [ ] 23

refactor: split facets sdk

---

.github/pull_request_template.md

This pull request updates the `.github/pull_request_template.md` file to improve clarity and guidance for contributors. The main changes focus on making the template instructions more explicit and helpful, especially in the description and testing sections.
Improvements to pull request template instructions:
* Expanded the "Description" section with clear guidance on what to include (what changed, why, relevant issues, and context), along with an example to help contributors write better summaries.
* Enhanced the "Testing" section by providing detailed instructions and examples for verifying changes, including both automated and manual testing steps, and clarified how to reference reproduction steps for bug fixes.
Checklist and formatting updates:
* Updated the Node version checklist and …

docs: update pull request template with hidden hints

---

packages/ats/contracts/test/unitTests/layer_1/ERC1400/ERC1410/erc1410.test.ts
packages/ats/contracts/test/unitTests/layer_1/ERC1400/ERC1594/erc1594.test.ts
packages/ats/contracts/test/unitTests/layer_1/ERC1400/ERC1643/erc1643.test.ts
packages/ats/contracts/test/unitTests/layer_1/ERC1400/ERC1644/erc1644.test.ts
packages/ats/contracts/test/unitTests/layer_1/ERC1400/ERC20/erc20.test.ts
packages/ats/contracts/test/unitTests/layer_1/ERC1400/ERC20Permit/erc20Permit.test.ts
packages/ats/contracts/test/unitTests/layer_1/ERC3643/erc3643.test.ts
packages/ats/contracts/test/unitTests/layer_1/accessControl/accessControl.test.ts
packages/ats/contracts/test/unitTests/layer_1/adjustBalances/adjustBalances.test.ts
packages/ats/contracts/test/unitTests/layer_1/bond/bond.test.ts
packages/ats/contracts/test/unitTests/layer_1/cap/cap.test.ts
packages/ats/contracts/test/unitTests/layer_1/clearing/clearing.test.ts
packages/ats/contracts/test/unitTests/layer_1/controlList/controlList.test.ts
packages/ats/contracts/test/unitTests/layer_1/corporateActions/corporateActions.test.ts
packages/ats/contracts/test/unitTests/layer_1/equity/equity.test.ts
packages/ats/contracts/test/unitTests/layer_1/hold/hold.test.ts
packages/ats/contracts/test/unitTests/layer_1/lock/lock.test.ts
packages/ats/contracts/test/unitTests/layer_1/pause/pause.test.ts
packages/ats/contracts/test/unitTests/layer_1/protectedPartitions/protectedPartitions.test.ts
packages/ats/contracts/test/unitTests/layer_1/scheduledTasks/scheduledBalanceAdjustments/scheduledBalanceAdjustments.test.ts
packages/ats/contracts/test/unitTests/layer_1/scheduledTasks/scheduledSnapshots/scheduledSnapshots.test.ts
packages/ats/contracts/test/unitTests/layer_1/scheduledTasks/scheduledTasks/scheduledTasks.test.ts
packages/ats/contracts/test/unitTests/layer_1/security/security.test.ts
packages/ats/contracts/test/unitTests/layer_1/securityUSA/securityUSA.test.ts
packages/ats/contracts/test/unitTests/layer_1/snapshots/snapshots.test.ts
packages/ats/contracts/test/unitTests/resolver/BusinessLogicResolver.test.ts
packages/ats/contracts/test/unitTests/resolver/diamondCutManager.test.ts
packages/ats/contracts/test/unitTests/resolverProxy/resolverProxy.test.ts

Remove reassignements in contracts vaiables tests.

fix: remove variable reassignments

---

apps/ats/web/src/views/DigitalSecurityDetails/Components/DangerZone.tsx
apps/ats/web/src/views/DigitalSecurityDetails/Components/__tests__/DangerZone.test.tsx
apps/ats/web/src/views/DigitalSecurityDetails/Components/__tests__/__snapshots__/DangerZone.test.tsx.snap

Add spinner in DangerZone component

Fix: [BBND-1085] spinner in danger zone

---

packages/ats/contracts/tasks/deploy.ts

fix: trex factory deployment task

---

apps/ats/web/src/views/CreateBond/Components/StepProceedRecipients.tsx
apps/ats/web/src/views/CreateBond/Components/StepReview.tsx
apps/ats/web/src/views/DigitalSecurityDetails/Components/ProceedRecipients/AddProceedRecipientModal.tsx
apps/ats/web/src/views/DigitalSecurityDetails/Components/ProceedRecipients/ProceedRecipients.tsx
apps/ats/web/src/views/DigitalSecurityDetails/Components/ProceedRecipients/UpdateProceedRecipientModal.tsx

Display text instead of hexadecimal in Data field in Proceed Recipients

fix: [BBND-1154] display data in text format
